version: '3.3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_ROOT_PASSWORD: 1234ABCD????
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"

  docker-app:
    restart: on-failure
    container_name: docker-app
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "8080"
    ports:
      - 8088:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  docker-front:
    restart: on-failure
    container_name: docker-front
    build:
      context: /Users/mac/Desktop/03-frontend/angular-ecommerce
      dockerfile: /Users/mac/Desktop/03-frontend/angular-ecommerce/Dockerfile

    ports:
      - 8089:80
    environment:
      WAIT_HOSTS: docker-app:8080
    depends_on:
      - docker-app
